[api]
enabled = true
port = 54321

[functions.sync-airbnb-calendars]
enabled = true

[functions.stripewebhook]
enabled = true
verify_jwt = false

[functions.emit-nfse]
enabled = true

[functions.send-booking-email]
enabled = true

[functions.send-checkin-reminder]
enabled = true

[functions.validate-promo]
enabled = true

[functions.checkoutstripe]
enabled = true

[functions.submit-fnrh]
enabled = true

[functions.cancel-reservation]
enabled = true

[functions.send-admin-message]
enabled = true

[functions.send-abandoned-booking]
enabled = true

[functions.send-review-request]
enabled = true
